### PR TITLE
Adding LBM-DEM

### PR DESCRIPTION
**Pull request by vtsinginos**
Adding the DEM-LBM using the PRE scheme

### CODE REVIEW

**Comment by jpmeng** [comment]
Hi Valantis, Shall we just need to keep the modification of MUI if any? Also, please delete all Executable. Jianping

**Comment by vtsinginos** [comment]
The MUI library was removed and a folder containing the LAMMPS fixes are added to the commit

**Comment by jpmeng** [comment]
Great. It seems that we have to also modify the compiling system of LAMMPS later to find MUI. I will merge this first.

**Comment by vtsinginos** [comment]
Or we can simply add the MUI folder into LAMMPS/src folder

**Comment by jpmeng** [comment]
> Or we can simply add the MUI folder into LAMMPS/src folder

No worry. The path issue can be easily solved for treating MUI as an external dependency.

**Pull request merged**
